# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnkinaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#ANKINA UI CODE VOICE BOT VERSION 1.0
#APP DEVELOPERS :-
#ANIKET BHATIA
#ANKIT GARG
#JOVINA JACINTA CASTELINO
#AAN SARAH ZACHARIAH

#Library Import Command
from PyQt5 import QtCore, QtGui, QtWidgets

#UI Class Define (CSS FORMATTING)
class Ui_AnkinaUI(object):
    def setupUi(self, AnkinaUI):
        AnkinaUI.setObjectName("AnkinaUI")
        AnkinaUI.resize(788, 726)
        self.centralwidget = QtWidgets.QWidget(AnkinaUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 841, 731))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 255, 230);\n"
"border-radius:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Aniket/Desktop/PYTHON PROJECT 310 DATA/__02-____.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 670, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(232, 190, 170);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 301, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Aniket/Desktop/PYTHON PROJECT 310 DATA/OccasionalBonyDugong-size_restricted.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(360, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(560, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"background-color: rgb(85, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        AnkinaUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnkinaUI)
        QtCore.QMetaObject.connectSlotsByName(AnkinaUI)

#BUTTONS AND MAIN WINDOW SETUP
    def retranslateUi(self, AnkinaUI):
        _translate = QtCore.QCoreApplication.translate
        AnkinaUI.setWindowTitle(_translate("AnkinaUI", "MainWindow"))
        self.pushButton.setText(_translate("AnkinaUI", "INITIATE"))
        self.pushButton_2.setText(_translate("AnkinaUI", "STOP"))

# DEFINE UI MAIN WINDOW
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnkinaUI = QtWidgets.QMainWindow()
    ui = Ui_AnkinaUI()
    ui.setupUi(AnkinaUI)
    AnkinaUI.show()
    sys.exit(app.exec_())
